language: node_js
node_js:
  - 'stable'
  - '5'
  - '4'
  - '0.12'
  - '0.10'

script:
  # Output useful info for debugging
  - node --version
  # Run tests and lint
  - npm test
  - npm run lint
  
notifications:
  email: false